branches:
  only:
    - master
    - PS_1.7
environment:
  tag_name: "%APPVEYOR_REPO_TAG_NAME%"
  release_name: "humm_prestashop_v%appveyor_repo_tag_name%.zip"
before_build:
  - ps: (Get-Content hummprestashop\config.xml).replace("humm_plugin_version_placeholder", $env:APPVEYOR_REPO_TAG_NAME ) | Set-Content hummprestashop\config.xml
  - ps: (Get-Content hummprestashop\hummprestashop.php).replace("humm_plugin_version_placeholder", $env:APPVEYOR_REPO_TAG_NAME ) | Set-Content hummprestashop\hummprestashop.php
build_script:
  - ps: Invoke-Expression "7z a $env:release_name hummprestashop"
artifacts:
  - path: $(release_name)
    name: $(tag_name)
    type: zip
deploy:
  - provider: GitHub
    tag: $(tag_name)
    release: v$(APPVEYOR_REPO_TAG_NAME)
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
    auth_token:
      secure: pBYYKQdFITLx5jBg61hqhb+UNrQyFQevWzo4ApLwduW+f54iu4QjDglXLidGMdCJ
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Email
    to:
      - devadmin@shophumm.com.au
  - provider: Slack
    auth_token:
      secure: yXpzER0fyDmh7wYR6zrrES+wGzz5010OpUvpb5UPMsQZO12Ag3TaeOjSsZ0tDQQ4WaNoNngsPOPiaYWmsfg3fhJrSyPy240FqSwDdhSPqC0=
    channel: '#alerts'