branches:
  only:
    - master/1.6
    - master/1.7
    - develop/1.6
    - develop/1.7
environment:
  tag_name: "%APPVEYOR_REPO_TAG_NAME%"
  release_name: "humm_prestashop_v%appveyor_repo_tag_name%.zip"
before_build:
  - ps: (Get-Content hummprestashop\config.xml).replace("humm_plugin_version_placeholder", $env:APPVEYOR_REPO_TAG_NAME ) | Set-Content hummprestashop\config.xml
  - ps: (Get-Content hummprestashop\common\HummCommon.php).replace("humm_plugin_version_placeholder", $env:APPVEYOR_REPO_TAG_NAME ) | Set-Content hummprestashop\common\HummCommon.php
build_script:
  - ps: Invoke-Expression "7z a $env:release_name hummprestashop"
artifacts:
  - path: $(release_name)
    name: $(tag_name)
    type: zip
deploy:
  - provider: GitHub
    tag: $(tag_name)
    release: v$(APPVEYOR_REPO_TAG_NAME)
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
    auth_token:
      secure: UaYGIzw09m+5DkdlA5zDuCr5x71z0KFvgquQhFSMxuJiUmltfok5GuMk8aGpG5U6
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Email
    to:
      - devadmin@shophumm.com.au
  - provider: Slack
    auth_token:
      secure: lgjOGAi/xfra+Ezjg696zGwfMyEivWbNo6ho9GwbeQConO2VwxX2txxjWrZVqAaxTtI7y/ODz0HG3uMfIiM5wF2Fa0KsT8I+KL7PW9BbzpQ=
    channel: '#alerts'